export const API_ERROR_CODES = {
  // auth
  EMAIL_EXISTS: "EMAIL_EXISTS",
  USERNAME_EXISTS: "USERNAME_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CURRENT_PASSWORD_INCORRECT: "CURRENT_PASSWORD_INCORRECT",
  // users
  CANNOT_DELETE_SELF: "CANNOT_DELETE_SELF",
  UPDATE_FAILED: "UPDATE_FAILED",
  DELETE_FAILED: "DELETE_FAILED",
  // skills / installs / assets / invoke
  SKILL_ALREADY_EXISTS: "SKILL_ALREADY_EXISTS",
  SKILL_NOT_FOUND: "SKILL_NOT_FOUND",
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  INSTALL_NOT_FOUND: "INSTALL_NOT_FOUND",
  NO_VERSIONS_FOUND: "NO_VERSIONS_FOUND",
  VERSION_UPDATE_FAILED: "VERSION_UPDATE_FAILED",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  MISSING_DATA_FIELD: "MISSING_DATA_FIELD",
  INVALID_DATA_JSON: "INVALID_DATA_JSON",
  // middleware
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  // generic
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]

export class ApiError extends Error {
  constructor(
    public code: ApiErrorCode,
    public status: number,
    message?: string
  ) {
    super(message ?? code)
    this.name = "ApiError"
  }
}
